repos:
-   repo: local
    hooks:
    -   id: validate-commit-message
        name: Validate Commit Message
        entry: ./scripts/validate_commit_message.py
        language: python
        files: ''
